<a href="https://colab.research.google.com/github/pongsaphakmw/AI_Builders/blob/main/Copy_of_ai_builder_entrace_exam_lite.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Entrace Example for AI Builders

จุดมุ่งหมายคือการทดสอบความรู้ปรับพื้นฐานสำหรับ AI Builders ทุกคำตอบสามารถหาได้จาก notebook ปรับพื้นฐาน `ai_builder_intro_python.ipynb`, `ai_builder_numpy.ipynb` และ `ai_builder_pandas.ipynb` 

เราหวังให้คุณพยามสุดความสามารถที่จะตอบ แต่ไม่จำเป็นต้องตอบได้ครบทุกข้อเพื่อที่จะได้รับการคัดเลือกเข้าโครงการ

## Python

1. หาก `a=1` และ `b=2.5` แล้ว, `c` = $0.5(a+2b^5)$, `c` มีค่าเท่าไหร่? $b^x$ เขียนใน Python ได้แบบนี้ `b**x`

In [ ]:
a=1
b=2.5
c = 0.5*a+2*b**5

2. `a`, `b`, และ `c` เป็นตัวแปรชนิดอะไรบ้าง? (ลองใช้ `type(a)`)

In [ ]:
type(a)

int

3. จากตัวแปร `s = 'AI Builders - A Program For Kids Who Wants to AI Good Good'`, เราจะดึงคำว่า `AI Good` ออกมาได้อย่างไร?

In [9]:
s = 'AI Builders - A Program For Kids Who Wants to AI Good Good'

#ใส่คำตอบตรงนี้
print(s.find('AI Good'))
print(s[46:54])


46
AI Good 


4. ใช้ loop `print` ทุก element ใน `l` ยกเว้น element ที่เขียนว่า `AI`

`l = ['AI','Builders','-','A','Program','For','Kids','Who','Wants','to','AI','Good','Good']`

ลองใช้ `for` และ `if` เพื่อกรอง element ที่มีค่าเป็น `AI` ออก

In [ ]:
l = ['AI','Builders','-','A','Program','For','Kids','Who','Wants','to','AI','Good','Good']

#เขียน loop ตรงนี้

for x in l:
  if x != 'AI':
    print(x)



Builders
-
A
Program
For
Kids
Who
Wants
to
Good
Good


5. เขียนฟังชั่น `midpoint` ที่หาจุดกึ่งกลางระหว่างตัวเลข `a` และ `b` 

In [18]:
def midpoint(a, b):
    return (a+b)/2
    """
    Computes a midpoint between a and b.
    Hint: midpoint of a and b is (a+b)/2
    """
    

print(midpoint(1, 4))  # expected 2.5
print(midpoint(3, 3))  # expected 3
print(midpoint(-2, 2))  # expected 0

2.5
3.0
0.0


6. เขียนฟังชั่น `fizzbuzz` ที่รับตัวเลข `x`


- ถ้า `x` หารด้วย 2 ลงให้คืน string ว่า `fizz`
- ถ้า `x` หารด้วย 3 ลงให้คืน string ว่า `buzz`
- ถ้า `x` หารด้วยทั้ง 2 และ 3 ลงให้คืน string ว่า `fizzbuzz`
- นอกนั้นให้คืน `None`

ลองใช้ `if`, `elif` และ `else` ในฟังชั่น `fizzbuzz`

In [86]:
def fizzbuzz(x):
  if x%2 == 0 and x%3 == 0:
    return 'fizzbuzz'
  elif x%2 == 0:
    return 'buzz'
  elif x%3 == 0:
    return 'fizz'
  else :
    return None

for i in range(20):
    print(i,fizzbuzz(i))

0 fizzbuzz
1 None
2 buzz
3 fizz
4 buzz
5 None
6 fizzbuzz
7 None
8 buzz
9 fizz
10 buzz
11 None
12 fizzbuzz
13 None
14 buzz
15 fizz
16 buzz
17 None
18 fizzbuzz
19 None


## Numpy and Linear Algebra

In [3]:
import numpy as np

1. สร้าง numpy array `a` ที่มีมิติ `3*3` โดยมีค่าเป็นตัวเลขจาก 1 ถึง 9 (ลองใช้ `np.arange` และ `np.reshape`)

In [20]:

a = np.arange(start=1, stop=10).reshape((3, 3)) #ใส่คำตอบตรงนี
a





array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2. สร้าง numpy array `b` ที่มีมิติ `4*3` โดยมีค่าเป็นตัวเลขจาก 1 ถึง 12 (ลองใช้ `np.arange` และ `np.reshape`)

In [21]:
b = np.arange(start=1, stop=13).reshape((4,3))#ใส่คำตอบตรงนี้
b 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

3. เราสามารถหาค่า `a` dot product `b` ได้หรือไม่-เพราะอะไร (ลองใช้ `a.dot(b)` หรือ `a@b`)

In [23]:
#ใส่คำตอบตรงนี้
a@b


ValueError: ignored

4. หาค่า `a` dot product (`b` transposed) (tranpose `b` ได้ด้วยคำสั่ง `b.T`)

In [24]:
#ใส่คำตอบตรงนี้
a@b.T


array([[ 14,  32,  50,  68],
       [ 32,  77, 122, 167],
       [ 50, 122, 194, 266]])

5. มิติ (แถวและคอลัมน์) ของ `a` และ `b` คืออะไร (ลองใช้ `a.shape`)

In [28]:
a.shape

#ใส่คำตอบตรงนี้


(3, 3)

6. คูณทุก element ของ `a` ด้วย -1

In [54]:
#ใส่คำตอบตรงนี้
a = np.arange(start=1, stop=10).reshape((3, 3)) #ใส่คำตอบตรงนี
a*(-1)


array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

7. เปลี่ยนมิติของ `b` ให้เป็น `2*2*3` (ลองใช้ `np.reshape`)

In [57]:
#ใส่คำตอบตรงนี้
b = np.arange(1,13).reshape((2,2,3))
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

8. ค่าเฉลี่ยของแต่ละแถวของ `a` (`3*3`) คืออะไร (ลองใช้ `np.mean` สังเกตว่าควรใช้ `axis=1` หรือ `axis=0`)

In [67]:
#ใส่คำตอบตรงนี้
a = np.arange(1,10).reshape((3,3)).mean(axis=1)
a



array([2., 5., 8.])

9. ค่าเฉลี่ยของแต่ละคอลัมน์ของ `a` (`3*3`) คืออะไร (ลองใช้ `np.mean` สังเกตว่าควรใช้ `axis=1` หรือ `axis=0`)

In [113]:
#ใส่คำตอบตรงนี้
a = np.arange(1,10).reshape((3,3)).mean(axis=0)
a

array([4., 5., 6.])

10. ถ้าเราต้องการหา `[[1,2],[4,5]]` จาก `a` เราต้องเลือกอย่างไร

In [126]:
#เราสามารถ slice แต่ละส่วนของ `np.array` ได้เหมือนกับ list เช่น 
a=np.array([[1,2],[4,5]])
a[:2]

array([[1, 2],
       [4, 5]])

In [127]:
#ใส่คำตอบตรงนี้
a=np.array([[1,2],[4,5]])
a[:2]

array([[1, 2],
       [4, 5]])

## Pandas and Data Exploration

ดาวน์โหลดชุดข้อมูล [อุบัติเหตุบนโครงข่ายถนนของกระทรวงคมนาคม 2562](https://data.go.th/dataset/roadaccident) (ไฟล์ชื่อ `ubatiehtuthaangthnn.xlsx`) จาก [data.go.th](https://data.go.th/). ตอบคำถามต่อไปนี้

In [3]:
import pandas as pd

1. อ่านไฟล์ `ubatiehtuthaangthnn.xlsx` เข้ามาเป็น `pandas.DataFrame`; `df` มีกี่แถว-คอลัมน์? (ลองใช้ `df.shape`)

In [4]:
url = 'https://archive.org/download/ubatiehtuthaangthnn/ubatiehtuthaangthnn.xlsx'
df = pd.read_excel(url)
df.shape

#ใส่คำตอบตรงนี้


(19965, 20)

2. เรียกดู 20 แถวแรกและ 20 แถวสุดท้ายของ `df` (ลองใช้ `df.head(20)` และ `df.tail(20)`)

In [ ]:
#ใส่คำตอบตรงนี้
df.head(20)
df.tail(20)

3. จังหวัดใดมีอุบัติเหตุเยอะที่สุดถ้าอ้างอิงจาก `df`? (ลองใช้ `df['จังหวัด'].value_counts()`)

In [ ]:
#ใส่คำตอบตรงนี้
df['จังหวัด'].value_counts()


4. เลือกเฉพาะแถวที่เป็นอุบัติเหตุที่มีผู้เสียชีวิต 0 ราย / มีอุบัติเหตุที่ไม่มีผู้เสียชีวิตกี่ครั้ง? (เราสามารถกรอง dataframe ได้ด้วยคำสั่ง `df[df['จำนวนผู้เสียชีวิต']==0]`)

In [ ]:
#ใส่คำตอบตรงนี้
df[df['จำนวนผู้เสียชวิต']==0]

5. ค่าเฉลี่ยของ latitude, logitude ของอุบัติเหตุที่เกิดขึ้นในจังหวัดเชียงใหม่อยู่ที่เท่าใด? (กรองให้เหลือแค่จังหวัดเชียงใหม่แล้วหาค่าเฉลี่ยด้วยคำสั่ง `df.LATITUDE.mean()` และ `df.LONGITUDE.mean()`)

In [107]:
#ใส่คำตอบตรงนี้
print(df[df['จังหวัด'] == 'เชียงใหม่'].LATITUDE.mean())
print(df[df['จังหวัด'] == 'เชียงใหม่'].LONGITUDE.mean())



18.91090138416936
98.91462670826341


6. `ลักษณะการเกิดอุบัติเหตุ ` แบบใดมี `จำนวนผู้เสียชวิต` โดยเฉลี่ยสูงที่สุด?

In [6]:
#Hint 1: df[COLUMN_NAME].value_counts().reset_index() will give you dataframe version of value counts
#Hint 2: See what sort_values() does

#ใส่คำตอบตรงนี้
df = df['ลักษณะการเกิดอุบัติเหตุ '] & df['จำนวนผู้เสียชวิต']
# df['ลักษณะการเกิดอุบัติเหตุ '].value_counts().reset_index()
# df = df[(df['closing_price'] >= 99) & (df['closing_price'] <= 101)]
# df['จำนวนผู้เสียชวิต'].value_counts().reset_index()
# df['จำนวนผู้เสียชวิต'].sort_values().value_counts()

TypeError: ignored

7. อุบัติเหตุที่เกิดจาก `มูลเหตุสันนิษฐาน` เป็น `ขับรถเร็วเกินกำหนด` มีโอกาสทำให้มีผู้เสียชีวิตมากกว่า `มูลเหตุสันนิษฐาน` อื่นหรือไม่?

In [38]:
#สร้าง column `drive_fast_flag` ที่จะเป็น 1 เมื่อ 'มูลเหตุสันนิษฐาน' เป็น 'ขับรถเร็วเกินกำหนด' (นอกนั้นเป็น 0) โดยใช้ map และ lambda
df['drive_fast_flag'] = df['มูลเหตุสันนิษฐาน'].map(lambda x: 1 if x=='ขับรถเร็วเกินกำหนด' else 0)

#สร้าง column `has_death` ที่จะเป็น 1 เมื่อ 'จำนวนผู้เสียชีวิต' มากกว่า 1 คน (นอกนั้นเป็น 0) โดยใช้ map และ lambda
df['has_death'] = df['จำนวนผู้เสียชวิต'].map(lambda x: 1 if x<=1 else 0)
df.groupby('drive_fast_flag').has_death.mean()
# print(df['has_death'])
#ใช้ groupby('drive_fast_flag').has_death.mean() เพื่อหาค่าเฉลี่ยของอุบัติเหตุที่มีผู้เสียชีวิต แบ่งด้วย drive_fast_flag


drive_fast_flag
0    0.974697
1    0.982247
Name: has_death, dtype: float64